export const roomates = [
  {
    "id": 1,
    "tipe": "busco",
    "nombre": "Benito",
    "apellido": "Camela",
    "edad": "20",
    "telefono": "125252365",
    "img": "1111.webp",
    "fecha_nacimiento": 95000,
    "correo": "sdaasda@edfdef.com",
  },
  {
    "id": 2,
    "tipe": "necesito",
    "nombre": "maria",
    "apellido": "Camela",
    "edad": "20",
    "telefono": "125252365",
    "img": "1111.webp",
    "fecha_nacimiento": 95000,
    "correo": "sdaasda@edfdef.com",
  },
  {
    "id": 3,
    "tipe": "busco",
    "nombre": "Benito",
    "apellido": "Camela",
    "edad": "20",
    "telefono": "125252365",
    "img": "1111.webp",
    "fecha_nacimiento": 95000,
    "correo": "sdaasda@edfdef.com",
  },
  {
    "id": 4,
    "tipe": "necesito",
    "nombre": "Benito",
    "apellido": "Camela",
    "edad": "20",
    "telefono": "125252365",
    "img": "1111.webp",
    "fecha_nacimiento": 95000,
    "correo": "sdaasda@edfdef.com",
  },
  {
    "id":5,
    "tipe": "busco",
    "nombre": "Benito",
    "apellido": "Camela",
    "edad": "20",
    "telefono": "125252365",
    "img": "1111.webp",
    "fecha_nacimiento": 95000,
    "correo": "sdaasda@edfdef.com",
  },
]